MainClass.class : MainClass.java
	javac MainClass.java

run : MainClass.class
	java MainClass

clean :
	rm MainClass.class
	rm AircraftCarrier.class
	rm Battleship.class
	rm Board.class
	rm Cruiser.class
	rm Destroyer.class
	rm Ship.class
	rm Submarine.class
	rm Tuple.class